version: "3"

services:
  wallet:
    container_name: server_wallet
    depends_on:
      - iliamongodb
    build: .
    command: npm run dev
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PRIVATE_KEY=${PRIVATE_KEY}

  iliamongodb:
    image: mongo
    container_name: iliamongodb
    ports:
      - '27017:27017'